runtime: nodejs20

env_variables:
  PORT: 4000
  MONGO: "mongodb+srv://iscoderz01:X6PsKONkOs6yHlAt@cluster0.k1lta4q.mongodb.net/"
  JWT_SECRET: "irjkjdkljalkjdjsojglksjklsdj"
  T_ACCOUNT_SID: "ACbf95ba9ab0e99dc01a6ee5d579cb0e16"
  T_AUTH_TOKEN: "b170e3cbe589d4d17295f116d97d96fd"
  T_VERIFY_SID: "VA5298db2e77a6a2a6283f077a5e6b929b"
